import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { hello } from "../requests/index";
import { useEffect } from "react";
import { useState } from "react";
import { toast } from "react-toastify";

const Home: NextPage = () => {
	const [response, setRes] = useState("");
	useEffect(() => {
		hello().then((res) => {
			console.log(res);
			setRes(JSON.stringify(res));
		});
	}, []);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>{response}</main>
		</div>
	);
};

export default Home;
